import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import type { Tool } from "@anthropic-ai/sdk/resources/messages.js";
import { IOS_APP_ROOT } from "./config.js";
import type { ToolName, AllowedTools } from "./types.js";

function appPath(p: string): string {
  return resolve(IOS_APP_ROOT, p);
}

const ALL_TOOL_DEFS: Record<ToolName, Tool> = {
  read_file: {
    name: "read_file",
    description: "Read a file at the given path relative to the iOS app root.",
    input_schema: {
      type: "object" as const,
      properties: {
        path: { type: "string", description: "File path relative to iOS app root" },
      },
      required: ["path"],
    },
  },
  write_file: {
    name: "write_file",
    description: "Write or overwrite a file at the given path relative to the iOS app root.",
    input_schema: {
      type: "object" as const,
      properties: {
        path: { type: "string", description: "File path relative to iOS app root" },
        content: { type: "string", description: "Content to write" },
      },
      required: ["path", "content"],
    },
  },
  bash_exec: {
    name: "bash_exec",
    description:
      "Execute a shell command in the iOS app root. Use for xcodebuild, swift test, git, etc. Timeout: 120s.",
    input_schema: {
      type: "object" as const,
      properties: {
        command: { type: "string", description: "Shell command to run (e.g. xcodebuild test)" },
      },
      required: ["command"],
    },
  },
  glob_files: {
    name: "glob_files",
    description: "List files by extension under a directory. Returns newline-separated relative paths.",
    input_schema: {
      type: "object" as const,
      properties: {
        dir: { type: "string", description: "Directory relative to iOS app root (e.g. 'src')" },
        ext: { type: "string", description: "File extension to match (e.g. '.swift')" },
      },
      required: ["dir", "ext"],
    },
  },
  grep_files: {
    name: "grep_files",
    description: "Search for a pattern in files. Returns matching lines with file:line context.",
    input_schema: {
      type: "object" as const,
      properties: {
        pattern: { type: "string", description: "Pattern to search" },
        path: { type: "string", description: "Directory or file to search (relative to app root)" },
      },
      required: ["pattern", "path"],
    },
  },
};

export function getToolDefs(allowed: AllowedTools): Tool[] {
  return allowed.map((name) => {
    const def = ALL_TOOL_DEFS[name];
    if (def === undefined) throw new Error(`Unknown tool: ${name}`);
    return def;
  });
}

type ToolInput = Record<string, string>;

export function executeTool(name: string, input: ToolInput): string {
  try {
    switch (name) {
      case "read_file": {
        const fullPath = appPath(input["path"] ?? "");
        if (!existsSync(fullPath)) return `ERROR: File not found: ${input["path"] ?? ""}`;
        return readFileSync(fullPath, "utf-8");
      }

      case "write_file": {
        const fullPath = appPath(input["path"] ?? "");
        writeFileSync(fullPath, input["content"] ?? "", "utf-8");
        return `OK: wrote ${input["path"] ?? ""}`;
      }

      case "bash_exec": {
        // bash_exec is intentionally a shell executor for agent-generated commands
        // (xcodebuild, swift test, git). Commands are generated by Claude agents,
        // not passed directly from end users.
        const cmd = input["command"] ?? "";
        const result = execFileSync("/bin/bash", ["-c", cmd], {
          cwd: resolve(IOS_APP_ROOT),
          timeout: 120_000,
          encoding: "utf-8",
          stdio: ["pipe", "pipe", "pipe"],
        });
        return result;
      }

      case "glob_files": {
        const dir = input["dir"] ?? ".";
        const ext = input["ext"] ?? "";
        const result = execFileSync("find", [appPath(dir), "-name", `*${ext}`, "-type", "f"], {
          encoding: "utf-8",
          timeout: 10_000,
        });
        return result || "(no matches)";
      }

      case "grep_files": {
        const pattern = input["pattern"] ?? "";
        const searchPath = appPath(input["path"] ?? ".");
        try {
          const result = execFileSync("grep", ["-rn", pattern, searchPath], {
            encoding: "utf-8",
            timeout: 10_000,
          });
          return result;
        } catch (e) {
          // grep exits 1 when no matches found — that's OK
          if (e instanceof Error && "status" in e && (e as NodeJS.ErrnoException & { status?: number }).status === 1) {
            return "(no matches)";
          }
          throw e;
        }
      }

      default:
        return `ERROR: Unknown tool: ${name}`;
    }
  } catch (err) {
    return `ERROR: ${err instanceof Error ? err.message : String(err)}`;
  }
}
